### ISSUE TITLE
Revisi sidang

### ISSUE THREAD

**Issue by rizqiaputri** [oktapascal/EMCN#10]
1. di master data bahan tidak usah ada stok
2. perhitungan BTKL dan BOP minta rincian perhitungannya (detail produksi)
3. tambahin jurnal biaya produksi 
4. tambahin proses produksi
5. jurnal pemakaian barang jadi harus pake ( BDP-Biaya Bahan Baku, BDP-Biaya Tenaga Kerja Langsung, BDP-Biaya Overhead Parik)
6. buku besar harus bisa mutasi per tahun dan per bulan
7. harga di form pemesanan tidak bisa diinputkan jadi harusnya langsung muncul harga nya setelah memasukan jenis pakaian dan jumlah pakaian
8. di detail pembelian yg tabel di jumlah (misal : kain jersey 30 meter, benang 2 pcs, tinta 300 ml)

**Comment by oktapascal** [comment]
Silahkan coba lagi, jangan lupa import database yang baru soalnya ada penambahan akun
