### ISSUE TITLE
Revisi EMCN

### ISSUE THREAD

**Issue by rizqiaputri** [oktapascal/EMCN#4]
1. jurnal sudah rata kanan dan belum ada Rp
2. yg ada Rp nya baru buku besar aja
3. HPP belum rata kanan dan belum ada Rp
4. Kartu HPPesanan belum rata kanan dan belum ada Rp 
5. yg di user produksi sm pemesanan nominal nya belum rata kanan dan belum ada Rp

**Comment by oktapascal** [comment]
Coba Download kembali. Udah di fix semalem soalnya

**Comment by rizqiaputri** [comment]
bang, kenapa ya kalau nginputin di pembelian bahan gaada pilihannya padahal udh aku inputin.
terus BBB 0 jadi error.
