### ISSUE TITLE
Master Data

### ISSUE THREAD

**Issue by rizqiaputri** [oktapascal/EMCN#6]
Bang mau nanya tentang master data, aku kurang paham.
jadi bang maksud di master data ada bahan, pakaian itu gimana? soalnya kemarin kan ditanyain sm bu nelsi, kenapa pas nginputin pembelian kaya gitu.
Makasih bang..

**Comment by oktapascal** [comment]
Emang mau gimana input pembeliannya ? master data bahan sama pakaian buat mengolah data bahan dan produk (pakaian) di studi kasus kamu. kalo gak ada master data bahan sama pakaian, aplikasi kamu gak bakal bisa jalan

**Comment by rizqiaputri** [comment]
nah kan di aplikasi aku tuh yg pembelian, langsung nginputin harga bahan baku atau bahan penolong nah kemarin ditanyain sm bu nelsi "kenapa kamu bisa langsung tau harga nya segitu, tanpa km menginputkan brp meter atau berapa banyak bahan yg dibutuhkan untuk memproduksi baju tsb" 
itu kan bang kita bisa tau berapa meter atau banyak nya tuh udh di inputin di BOM?

**Comment by oktapascal** [comment]
iya itu di bom, misalnya ada pesanan buat bikin baju jersey. buat bikin baju jersey itu diketahui butuh 2 meter kain dan 2 roll benang. terus kita beli kain ke vendor kain, misal si vendor masang tarif 1 meter kain = 10.000 dan 1 roll benang = 5.000. karena baju jersey butuh 2 meter kain dan 2 roll benang jadinya 10.000 x 2 meter = 20.000 total harga untuk kain dan 5.000 x 2 roll = 10.000 total harga benang
