### ISSUE TITLE
revisi BOM

### ISSUE THREAD

**Issue by rizqiaputri** [oktapascal/EMCN#7]
bang, kan di pakaian aku ada baju bola nya berbagai macam ukuran S, M, L, XL
ini teh yg mau ditambah keterangan ukuran pas nambah BOM, soalnya kan ntar BOM nya itu dilihat dr baju apa dan ukuran apa aja, soalnya kan BOM nyambungnya ke transaksi pembelian.
makasih bang..

**Comment by oktapascal** [comment]
Udah diupdate, coba lagi
