### ISSUE TITLE
Revisi dr bu nelsi

### ISSUE THREAD

**Issue by rizqiaputri** [oktapascal/EMCN#8]
bang kata bu nelsi, bu nelsi pengen ada : 
1. tanggal awal pemesanan nyaa di pas pemesanan
2. di pembelian, yg data pembelian kan ada jumlah ya bang nah si ibu minta jumlah itu pake satuan (misal : kain jersey 20 meter, benang jahit 5 pcs, tinta sublime 100 ml)
3. buku besar kop nya lengkapi (ntar fotonya aku kirim ke teh rike ya bang buat contohnya)
4. tanggal saldo awal sm saldo akhir itu kenapa 0 bang, soalnya tadi ditanyain itu
makasih bang..

**Comment by oktapascal** [comment]
Point 1 sampe 3 udah diupdate bisa dicoba lagi, untuk point nomor 4 itu dari dulu untuk saldo awal dan akhir tanggalnya emang di set 0000-00-00 (yang diajarkan pak kastaman) punya si salma juga kaya gitu kok dan gak dimasalahin ketika sidang
