### ISSUE TITLE
Perhitungan produksi

### ISSUE THREAD

**Issue by rizqiaputri** [oktapascal/EMCN#9]
bang, ini di perhitungan produksi baru aku cek lg ternyata total perhitungan bop buat bahan penolongnya blm sesuai sm pembelian.
Soalnya kan rumusnya bop nya taksiran bop / taksiran jmlh yg dihasilkan hasilnya dikali dgn jumlah pesanan dan ditambah biaya bahan penolong. Nah bahan penolong belum sesuai sm di pembelian
makasih bang..

**Comment by rizqiaputri** [comment]
bang, buku besar kas ini kan msh minus pengen ga minus gimana cara nya? yg kemarin salma mah kan ngga minus ya bang

**Comment by oktapascal** [comment]
Buat revisi aja, telat kamu ngasih taunya. Saya gamau revisi H-1 sidang
